# Generated by Django 6.0.2 on 2026-03-03 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='sub',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
