# Generated by Django 6.0.2 on 2026-03-02 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AnalysisModel',
            new_name='Items',
        ),
        migrations.RenameField(
            model_name='items',
            old_name='title',
            new_name='name',
        ),
    ]
