# Generated by Django 6.0.2 on 2026-03-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0003_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='total_subscribers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_videos',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
