# Generated by Django 6.0.2 on 2026-03-10 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0004_user_total_subscribers_user_total_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_analyzed',
            field=models.BooleanField(default=False),
        ),
    ]
