# Generated by Django 6.0.2 on 2026-03-12 21:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0005_user_is_analyzed'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video_count', models.IntegerField(default=0)),
                ('total_comments', models.IntegerField(default=0)),
                ('avg_sentiment', models.FloatField(default=0.0)),
                ('positive_percent', models.FloatField(default=0.0)),
                ('neutral_percent', models.FloatField(default=0.0)),
                ('negative_percent', models.FloatField(default=0.0)),
                ('top_video_id', models.CharField(blank=True, max_length=50, null=True)),
                ('top_video_title', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
