# Generated by Django 6.0.2 on 2026-03-16 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0006_analysissnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_comment_id', models.CharField(max_length=100, unique=True)),
                ('text', models.TextField()),
                ('author', models.CharField(max_length=255)),
                ('published_at', models.DateTimeField()),
                ('sentiment_score', models.FloatField(blank=True, null=True)),
                ('sentiment_label', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='backtube1.video')),
            ],
        ),
    ]
