# Generated by Django 6.0.2 on 2026-03-24 13:57

import pgvector.django.vector
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0007_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='title_embedding',
            field=pgvector.django.vector.VectorField(blank=True, dimensions=1536, null=True),
        ),
    ]
