# Generated by Django 6.0.2 on 2026-03-24 13:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0008_video_title_embedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cluster_label', models.IntegerField()),
                ('cluster_name', models.CharField(blank=True, max_length=255, null=True)),
                ('avg_views', models.FloatField(default=0)),
                ('avg_engagement', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clusters', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='cluster',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='backtube1.topiccluster'),
        ),
    ]
