# Generated by Django 6.0.2 on 2026-04-07 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backtube1', '0009_topiccluster_video_cluster'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCache',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=255, unique=True)),
                ('results', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
